### ISSUE TITLE
Error during MAKE

### ISSUE THREAD

**Issue by jah-jh** [lukepalmer/brubeck-new#9]
Got error in make
`src/backends/kafka.c:40:9: warning: implicit declaration of function 'rd_kafka_fatal_error'; did you mean 'rd_kafka_last_error'? [-Wimplicit-function-declaration]
   err = rd_kafka_fatal_error(self->rk, errstr, sizeof(errstr));
         ^~~~~~~~~~~~~~~~~~~~
         rd_kafka_last_error
src/backends/kafka.c: In function 'error_cb':
src/backends/kafka.c:96:14: error: 'RD_KAFKA_RESP_ERR__FATAL' undeclared (first use in this function); did you mean 'RD_KAFKA_RESP_ERR__FAIL'?
   if (err != RD_KAFKA_RESP_ERR__FATAL)
              ^~~~~~~~~~~~~~~~~~~~~~~~
              RD_KAFKA_RESP_ERR__FAIL
src/backends/kafka.c:96:14: note: each undeclared identifier is reported only once for each function it appears in
make: *** [src/backends/kafka.o] Error 1`

**Comment by lukepalmer** [comment]
Try installing the package 'librdkafka-dev' on your build machine.

That being said, you might not want kafka and I think it should be optional (#5)

**Comment by lukepalmer** [comment]
Also make sure you are using the official Confluent APT repository. Some linux distibutions will pull in stale versions by default.
 
https://github.com/edenhill/librdkafka#installing-prebuilt-packages

**Comment by lukepalmer** [comment]
Closing with no response, please re-open if there's a problem
